### ISSUE TITLE
Reconsidering the differentiation between the GWP of fossil and non-fossil methane

### ISSUE THREAD

**Issue by robyistrate** [polca/premise_gwp#4]
Given that biogenic and fossil CO2 are now treated equally (i.e., with a GWP +1), it may be worth reconsidering the differentiation between the GWP of fossil and non-fossil methane. I think that the same GWP (i.e., that of fossil methane) should be used for both methane flows. This change can have quite a large impact on the carbon footprint of, e.g., biomethane-based systems.

Ref: Table 5 in Muñoz and Schmidt, DOI: 10.1007/s11367-016-1091-z

**Comment by romainsacchi** [comment]
Hi @robyistrate, thanks. I see. 

As it stands, the GWP for CH4 in `premise_gwp` (which is a copy of ecoinvent's implementation of IPCC 2013) is 29.7 for fossil-based and 28.5 for biogenic-based.

Do you suggest having 29.7 for both as written in Muñoz and Schmidt "However, if we decided to treat all carbon as equal, a single GWP100 value would be required, namely that for fossil methane, which would be applied regardless of the carbon origin"?

However, the value Muñoz and Schmidt suggest for fossil CH4, including oxidation, is 30.5, not 29.7 as in `premise_gwp`.
Do you think the GWP for both biogenic and fossil CH4 should be changed to 30.5? FYI, it is 29.8 for CH4 in IPCC 2021.

**Comment by robyistrate** [comment]
To be fully consistent, I suggest to retain the GWP for fossil methane in the underlaying impact assessment method. For the current version of premise_gwp I would use the value of 29.7, as outlined in IPCC 2013.

**Comment by romainsacchi** [comment]
Done!

**Comment by romainsacchi** [comment]
Hi @robyistrate,

looking back at this issue, I'm not entirely sure that the point Munoz and Schmidt are trying to make is what we actually implemented. To me, it seems they insist on keeping a difference of 2.75 kg CO2-eq. between fossil and biogenic methane, as soon as one starts to discriminate biogenic from fossil GHG. Or am I wrong?

**Comment by romainsacchi** [comment]
Right, the 2.75 kg CO2-eq. difference is only required when biogenic CO2 is ignored. When accounted for, both biogenic and fossil methane should have the fossil methane GWP value.

**Comment by robyistrate** [comment]
Hi Romain,

I agree. The same GWP value for biogenic and fossil methane is required when biogenic CO2 is not neutral (i.e., GWP +1). If biogenic CO2 is considered neutral (i.e., GWP +0), then the differentiation between biogenic and fossil methane makes sense (i.e., as implemented in the IPCC method). I'm not sure what was the implementation issue here?
